# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180808_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default='Male', max_length=1),
        ),
    ]
